### ISSUE TITLE
Familiarization with Drools Fusion

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT#1]
### Why
While testing Drools Fusion as a candidate for CONSERT Engine CEP reasoning we need to know how to perform a setup and base run of the engine.

### What
 - [ ] Document setup and running of Drools Fusion
 - [ ] Implement toy example showcasing:
   - creating and inserting events
   - writing of rules
   - running the rules and collecting output

Document steps for successful setup and running of Drools Fusion engine

**Comment by funkydvd** [comment]
setup and running of Drools Fusion:
1. Download sources from http://download.jboss.org/drools/release/ or http://drools.jboss.org/downloads
2. Go to eclipse, help -> install new software and add the folder binaries/org.drools.updatesite that you have already downloaded
3. After the install, you can simply make a new Drools project, by accessing file -> new project -> drools project

Toy example is already implemented here: https://github.com/DuncanDoyle/simple-drools-cep

[setup and running of Drools Fusion.pdf](https://github.com/ami-lab/CONSERT/files/780331/setup.and.running.of.Drools.Fusion.pdf)
