### ISSUE TITLE
New Drools Project for AmI-Lab HLA recognition

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT#10]
### Why
Following the outline of #9, we need to create a new Drools project to implement the AmI-Lab HLA recognition scenario.

### What
 * [ ] a new branch is created that corresponds to the #9 epic. The branch will act as master substitute until AmI-Lab HLA project is finished.
 * [ ] necessary steps for Drools project creation are documented in a Readme.md file
 * [ ] project skeleton (see comments in #1 for inspiration) is created and pushed  

### NOTES

**Comment by funkydvd** [comment]
https://github.com/ami-lab/CONSERT/tree/9-hla-recognition-scenario
