### ISSUE TITLE
Create event model for AmI-Lab HLA recognition demo

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT#11]
### Why
Following the outline in #9, we need to create the set of Java POJOs which model the information captured by events and entities in the AmI-Lab HLA recognition demo.

### What
 * [x] the set of Java classes that model the AmI-Lab HLA events, as well as their meta properties are created

**Comment by funkydvd** [comment]
https://github.com/ami-lab/CONSERT/tree/9-hla-recognition-scenario
