### ISSUE TITLE
Write AmI-Lab HLA detection rules

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT#13]
### Why
Following the outline of #9, we want to implement the AmI-Lab HLA detection scenario using the Drools Rule Language, to familiarize ourselves with temporal operators and diverse filtering options. 

### What
 * [ ] the rules that had been defined in the ETALIS based implementation of the AmI-Lab HLA scenario are rewritten for Drools Fusion and tested on the event stream produced by the parser developed in #12.

**Comment by mihai-trascau** [comment]
Successfully created and tested rule for Working HLA.

**Comment by asorici** [comment]
To complete this issue the following need to still be done (letting @funkydvd be in charge):
  - [ ] write rule for detecting DiningHLA
