### ISSUE TITLE
Implement temporal validity extension mechanism for events in AmI-Lab HLA scenario

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT#14]
### Why
Following the outline in #9, the AmI-Lab HLA detection demo is meant to create a scenario where extension of the temporal validity of arriving atomic events is a useful feature in detecting high-level activities. 
We need to test the capability of Drools Fusion to reliably handle such a use case.

### What
  * [x] a means to retrieve the latest event in a given stream (Entrypoint in Drools Fusion) is documented and implemented
  * [x] a mechanism to analyze whether temporal validity extension is permitted when a new __atomic event__ arrives is implemented
  * [x] a mechanism to _create/update_ the validity of an __interval event__ based on new __atomic events__ is implemented (see comments in #2)
  * [x] separate entrypoints are created in the project for the __atomic events__ parsed from an input file and for the __interval events__ created/updated by the validity extension mechanism

### Notes
There will be an event stream for each event type defined in the AmI-Lab HLA detections scenario (e.g. "PositionStream", "LLAStream"). The __atomic events__ parsed from an input file will be inserted in these streams.

For each event type, a separate interval-based stream is created (e.g. "PositionExtendedStream", "LLAExtendedStream").

The validity extension mechanism must run _after_ the new atomic event is inserted into its corresponding stream.
The mechanism will need to retrieve the latest interval event from the corresponding interval-based entrypoint, check if the new atomic event allows for an extension and, if so, update the validity of the interval event.

**Comment by asorici** [comment]
After going through the Drools documentation, I found the concept of a rule execution [Agenda](https://docs.jboss.org/drools/release/6.5.0.Final/drools-docs/html/ch07.html#d0e6889) and [AgendaGroups](https://docs.jboss.org/drools/release/6.5.0.Final/drools-docs/html/ch07.html#d0e6942). 

This opens the possibility to implement the extension mechanism using rules in Drools.
Every time an atomic event is inserted, we first run the rules that check for extension possibility (and later consistency), and afterwards all domain rules (the actual HLA detection rules).

**Comment by mihai-trascau** [comment]
Current working version has been tested. Future modification should open new issue.
Closing.
