### ISSUE TITLE
Event inserter

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT#17]
### Why
Starting from the progress made in #12, a means to insert the parsed atomic events in their corresponding streams is required to bring them into the engine working memory.

### What
  * [x] Implement the inserter as a separate thread
  * [x] Create a stream for Position events and one for LLA events
  * [x] Use Java Timers to submit insert requests based on the timestamp difference between consecutive parsed events.

**Comment by mihai-trascau** [comment]
Current working version has been tested. Future modification should open new issue.
Closing.
