### ISSUE TITLE
Visualize result of HLA Detection Scenario

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT#19]
### Why
In order to validate the HLA Detection Scenario using the proposed temporal validity extension mechanism we require a means to visualize all the individual detected HLAs (along with their corresponding validity intervals and certainty values)

### What
  - [x] create a method to store/retrieve the latest/longest of each of the detected HLAs
  - [x] run detection scenario end-to-end and create a small visualization tool. The tool must allow to follow a timeline for each HLA type and see the validity intervals for HLA instances of that type (along with certainty level).

### Notes
A display tool in Python was already created by @mihai-trascau. Consider option to export scenario results to a JSON format and use existing display tool.

**Comment by mihai-trascau** [comment]
Plotly was used instead of the old tool (which used matplotlib). JSON files with the entire knowledge-base (per entrypoint) are exported and used by a visualization script.
