### ISSUE TITLE
Drools Fusion Extension Capabilities

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT#2]
### Why
While studying Drools Fusion as candidate for CONSERT CEP processing, we need to know what the possible extension capabilities are which allow us to implement custom workflow of CONSERT.

### What
 - [x] Document describing extension point for event temporal validity extension (start investigation from this [forum post](http://drools-moved.46999.n3.nabble.com/rules-users-Drools-Fusion-updating-event-duration-td3767583.html))
 - [x] Document describing extension point for pre-event insertion hook - to apply constraint checking
 - [x] Document describing means to perform event retraction

**Comment by funkydvd** [comment]
[drools_temporal_validity_extension.pdf](https://github.com/ami-lab/CONSERT/files/799251/drools_temporal_validity_extension.pdf)

**Comment by funkydvd** [comment]
[Retract_event_drools.pdf](https://github.com/ami-lab/CONSERT/files/817012/Retract_event_drools.pdf)

**Comment by funkydvd** [comment]
[drools_constraint_checking.pdf](https://github.com/ami-lab/CONSERT/files/850989/drools_constraint_checking.pdf)
