### ISSUE TITLE
Cover Eclipse Plugin Creation

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT#6]
### Why

As a CONSERT IDE developer I want to know how to make use of existing IDE/plugin development technologies to achieve the desired functional requirements.

### What
  - [ ] perform tutorial for Eclipse 4.x plugin creation; document the main take-aways
  - [ ] explore and document options for custom GUI development
  - [ ] document suggestions for each UI element from CONSERT interface mockup (i.e. document contains a mapping from functional requirement to set of GUI elements))

**Comment by emiliapopa** [comment]
Started the tutorial for Eclipse 4.x plugin creation;
Created a document in which the essential steps and main take-aways are introduced.
https://docs.google.com/document/d/1D7-tH9voxz9xoFG_-PGHHydR20OwA94Q6T8uMTpaL8k/edit

**Comment by asorici** [comment]
@emiliapopa Please add the Google Doc with the Tutorial for IDE development in the shared [Google Drive Folder](https://drive.google.com/drive/folders/0B_fjaGbXUSPIWjVNcEZha3U1dTA?usp=sharing).
That way all team members can access it :-)

Thanks.

**Comment by emiliapopa** [comment]
@asorici I updated the link in my initial comment. 

Sorry for the mistake :)

**Comment by asorici** [comment]
Issue moved to [ami-lab/CONSERT-IDE #3](https://github.com/ami-lab/CONSERT-IDE/issues/3) via [**ZenHub**](https://www.zenhub.com/)
